const ONE_SECOND_IN_MILLISECONDS = 1000;
const GIGASECOND = 1E9;
const GIGASECOND_IN_MILLISECONDS = GIGASECOND * ONE_SECOND_IN_MILLISECONDS

export const gigasecond = (inputDate) => 
  new Date(inputDate.getTime() + GIGASECOND_IN_MILLISECONDS );
;